-keep class org.webrtc.** { *; }
-keep class com.google.devtools.build.android.desugar.runtime.** { *; }
-dontwarn org.webrtc.**
-keep class com.squareup.okhttp3.** { *; }
-dontwarn com.squareup.okhttp3.**
-keep class kotlinx.coroutines.** { *; }